import jax.numpy as jnp
from jax.scipy.stats import poisson, norm
import math
import jax


class Classifier:
    def __init__(self, priors: list[float], parameters: list[dict[str, float]]):
        self.logpriors = jnp.log(jnp.array(priors))
        self.parameters = parameters
        self.category_count = len(parameters)

    def loglikelihood(
        self, inrec: tuple[float, int, int, bool], params: dict[str, float]
    ) -> float:
        # Returns the log of the likelihood that inrec would be generated by the
        # model defined by params
        ## Your code here
        
        # We want to find the likelihoods for all the features (area, visitors1 count, visitors2 count, felon?)
        # The features are indepedent, so we can find the likelihoods with the:
        # 1. PDF of the area
        # 2. PMF of the visitors
        # 3. Probability of being a felon
        # We are in log space here, so add instead of multiply.

        area_pdf = jax.scipy.stats.norm.logpdf(inrec[0], params["mu_a"], params["std_a"])

        # logpmf also has a loc parameter for shifting, not needed here
        visitors_1 = jax.scipy.stats.poisson.logpmf(inrec[1], params['lambda_v'])
        visitors_2 = jax.scipy.stats.poisson.logpmf(inrec[2], params['lambda_v'])

        # p(felon) was just normal probability. Need to make sure we convert it to log space
        # for smooth calculations of the overall log likelihood.
        felon = jnp.log(params["s"] if inrec[3] else 1 - params['s'])

        return area_pdf + visitors_1 + visitors_2 + felon


    # Take in one data point: [area, visitors1, visitors2, felon]
    def predict(self, inrec: tuple) -> jnp.ndarray:
        # Returns a vector of the probability of each class
        # (should sum to 1.0)
        ## Your code here
        # area, visitors1, visitors2, felon = inrec

        # SOLUTION 1:

        # # We first find the unnormalized log posterior for each class.
        # # Note that there are only two classes (laundromat, depot)
        # logposterior = jnp.zeros(self.category_count)

        # # For each class, we add the loglikelihood that the class is predicted, and the prior for that class
        # # Note that this loop only runs twice, because we have two categories and two classes.
        # for i in range(self.category_count):
        #     logposterior = logposterior.at[i].set(self.loglikelihood(inrec, self.parameters[i]) + self.logpriors[i])
        
        # # Log-sum-exp trick.
        # # We just return to raw probabilities by taking jnp.exp(). Then just normalize by dividing values in
        # # the array by the sum of all the values.
        # posterior = jnp.exp(logposterior)
        # posterior = posterior / jnp.sum(posterior)
        # return posterior

        # SOLUTION 2:
        # This solution if more efficient because it does not use a loop
        # It takes advantage of the fact that we only have two classes
        log_posterior_0 = self.loglikelihood(inrec, params=self.parameters[0]) + self.logpriors[0]
        log_posterior_1 = self.loglikelihood(inrec, params=self.parameters[1]) + self.logpriors[1]

        posterior_0 = jnp.exp(log_posterior_0)
        posterior_1 = jnp.exp(log_posterior_1)

        total_posterior_unnorm = posterior_0 + posterior_1
        return jnp.array([posterior_0 / total_posterior_unnorm, posterior_1 / total_posterior_unnorm])
